"""initial schema

Revision ID: e399e466a699
Revises: 
Create Date: 2026-07-03 00:50:22.601425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_stage', sa.String(), nullable=False),
    sa.Column('strand', sa.String(), nullable=False),
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('edexcel_ref', sa.String(), nullable=True),
    sa.Column('difficulty_band', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_table('lesson_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('lesson_notes', sa.Text(), nullable=True),
    sa.Column('worked_examples', sa.Text(), nullable=True),
    sa.Column('key_vocabulary', sa.Text(), nullable=True),
    sa.Column('common_errors', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_cache_id'), 'lesson_cache', ['id'], unique=False)
    op.create_table('question_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_cache_id'), 'question_cache', ['id'], unique=False)
    op.create_table('regeneration_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regeneration_log_id'), 'regeneration_log', ['id'], unique=False)
    op.create_table('teaching_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('taught_date', sa.Date(), nullable=False),
    sa.Column('class_label', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_log_id'), 'teaching_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teaching_log_id'), table_name='teaching_log')
    op.drop_table('teaching_log')
    op.drop_index(op.f('ix_regeneration_log_id'), table_name='regeneration_log')
    op.drop_table('regeneration_log')
    op.drop_index(op.f('ix_question_cache_id'), table_name='question_cache')
    op.drop_table('question_cache')
    op.drop_index(op.f('ix_lesson_cache_id'), table_name='lesson_cache')
    op.drop_table('lesson_cache')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
